# Generated by Django 5.1.3 on 2025-03-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commentaire_likes_reponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
    ]
