# Generated by Django 6.0.1 on 2026-01-26 22:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
