# Generated by Django 6.0.1 on 2026-02-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_contenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='auteur',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
    ]
