# Generated by Django 6.0.1 on 2026-02-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_reponse_commentaire_remove_reponse_auteur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='auteur',
        ),
    ]
