# Generated by Django 6.0.1 on 2026-02-03 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_article_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='vues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.article')),
            ],
            options={
                'unique_together': {('article', 'ip_address')},
            },
        ),
    ]
