# Generated by Django 6.0.1 on 2026-02-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
    ]
